name: Go Checks

on:
  pull_request:
    paths:
      - '**.go'

jobs:
    gofmt:
        name: Check Code Format
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.20
            
            - name: Check formatting
              run: |
                FILES=$(gofmt -l .)
                if [ -n "$FILES" ]; then
                echo "These files are not formatted correctly:"
                echo "$FILES"
                exit 1
                fi

    govet:
        name: Vet Code
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.20

        - name: Vet
          run: go vet ./...