name: Unit Tests

# Runs unit tests for pull requests and pushes to main
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit:
    strategy:
      matrix:
        go-version: [1.21.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go mod download
      - name: Run unit tests
        run: go test -count=1 -timeout=30s -parallel=4 ./... -v